print("A soma de 6+2", end=" ")
print(6+2)
print("A subtração de 6-2", end=" ")
print(6-2)
print("A multiplicação de 6*2", end=" ")
print(6*2)
print("A divisão de 6/2", end=" ")
print(6/2)
print("A exponenciação de 6**2", end=" ")
print(6**2)
